class global_vars:
    input_features = [
        "depth",
        "imu_roll",
        "imu_pitch",
        "imu_yaw",
        "imu_roll_angvel",
        "imu_pitch_angvel",
        "imu_yaw_angvel",
        "imu_x_linacc",
        "imu_y_linacc",
        "imu_z_linacc",
        "diffp_j1",
        "diffp_j2",
        "diffp_j3",
        "diffp_j4",
        "pos_x",
        "pos_y",
        "pos_z",
        "pos_roll",
        "pos_pitch",
        "pos_yaw",
        "hydraulic_pressure",
    ]
    output_features = ["Fx", "Fy", "Fz", "Mx", "My", "Mz"]
